import type { LibItem } from './types';

/**
 * 자료실·나의 자료 공통 목업 (프로토타입 LIB/MY 상당).
 * Phase B API 연동 시 제거하거나 Story/테스트용으로만 유지.
 * taxonomy value(`filterTaxonomy`)와 맞춰 두어 칩 필터가 동작한다.
 * `createdAt`은 variant=my 카드 표시용 (ISO).
 */
export const MOCK_LIBRARY_ITEMS: LibItem[] = [
  {
    id: 'l1',
    title: '감정 체크인 카드',
    src: 'verified',
    selArea: '자기인식',
    colorGroup: 'g1',
    views: 1240,
    saves: 328,
    createdAt: '2026-07-14T00:00:00',
    provider: '피어나다',
    level: ['초'],
    grade: ['초3'],
    duration: '40분',
    factors: ['감정인식', '감정조절'],
  },
  {
    id: 'l2',
    title: '관계 역할극 시나리오',
    src: 'verified',
    selArea: '관계기술',
    colorGroup: 'g2',
    views: 980,
    saves: 210,
    createdAt: '2026-07-13T00:00:00',
    provider: '온리원',
    level: ['중'],
    grade: ['중1'],
    duration: '45분',
    factors: ['공감', '의사소통'],
  },
  {
    id: 'l3',
    title: '자기관리 워크시트',
    src: 'unverified',
    selArea: '자기관리',
    colorGroup: 'g3',
    views: 540,
    saves: 96,
    createdAt: '2026-07-12T00:00:00',
    provider: '비상',
    level: ['초'],
    grade: ['초5'],
    duration: '5분',
    factors: ['목표설정', '강점인식'],
  },
  {
    id: 'l4',
    title: '갈등 해결 시나리오',
    src: 'verified',
    selArea: '책임있는의사결정',
    colorGroup: 'g4',
    views: 1520,
    saves: 441,
    createdAt: '2026-07-08T00:00:00',
    provider: '연구단',
    level: ['중'],
    grade: ['중2'],
    duration: '50분',
    factors: ['갈등해결', '문제해결'],
  },
  {
    id: 'l5',
    title: '정서 안정 호흡 활동',
    src: 'external',
    selArea: '자기관리',
    colorGroup: 'g5',
    views: 320,
    saves: 58,
    createdAt: '2026-07-15T00:00:00',
    provider: '교육청',
    level: ['고'],
    grade: ['고1'],
    duration: '80분',
    factors: ['감정조절', '감정인식'],
  },
  {
    id: 'l6',
    title: '우리 반 강점 찾기',
    src: 'internal',
    selArea: '사회적인식',
    colorGroup: 'g6',
    views: 210,
    saves: 44,
    createdAt: '2026-07-05T00:00:00',
    provider: '피어나다',
    level: ['초'],
    grade: ['초6'],
    duration: '40분',
    factors: ['강점인식', '공감'],
  },
];
